services:
  - type: web
    name: task-manager-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn task_manager.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: task_manager.settings
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: task-manager-api.onrender.com
